[2018-12-09 13:58:09] ---------TraceErr---------
Traceback (most recent call last):
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 36, in run
    self.Recv(sData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 58, in Recv
    self.OnCommand(dPackData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 108, in OnCommand
    commandctrl.OnCommand(self, dData)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\__init__.py", line 15, in OnCommand
    oManager.OnCommand(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\mutexlock\__init__.py", line 18, in ___AutoLock
    ret = func(*args, **kwargs)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\manager.py", line 60, in OnCommand
    oFunc(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 116, in OnGetRank
    pubglobalmanager.CallManagerFunc("demo", "GetRank", oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\pubglobalmanager.py", line 30, in CallManagerFunc
    return oFunc(*args)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 90, in GetRank
    rankList[i] = [row[0], row[1], row[2]]
IndexError: list assignment index out of range
---------extra---------
recvfail2
[2018-12-09 13:58:56] ---------TraceErr---------
Traceback (most recent call last):
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 36, in run
    self.Recv(sData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 58, in Recv
    self.OnCommand(dPackData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 108, in OnCommand
    commandctrl.OnCommand(self, dData)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\__init__.py", line 15, in OnCommand
    oManager.OnCommand(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\mutexlock\__init__.py", line 18, in ___AutoLock
    ret = func(*args, **kwargs)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\manager.py", line 60, in OnCommand
    oFunc(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 117, in OnGetRank
    pubglobalmanager.CallManagerFunc("demo", "GetRank", oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\pubglobalmanager.py", line 30, in CallManagerFunc
    return oFunc(*args)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 90, in GetRank
    rankList[i] = [row[0], row[1], row[2]]
IndexError: list assignment index out of range
---------extra---------
recvfail2
[2018-12-12 19:16:43] ---------TraceErr---------
Traceback (most recent call last):
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 36, in run
    self.Recv(sData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 54, in Recv
    self.OnCommand(dPackData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 104, in OnCommand
    commandctrl.OnCommand(self, dData)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\__init__.py", line 15, in OnCommand
    oManager.OnCommand(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\mutexlock\__init__.py", line 18, in ___AutoLock
    ret = func(*args, **kwargs)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\manager.py", line 53, in OnCommand
    oFunc(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 116, in OnSubmit
    pubglobalmanager.CallManagerFunc("demo", "Submit", oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\pubglobalmanager.py", line 30, in CallManagerFunc
    return oFunc(*args)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 95, in Submit
    rank.SubmitRecord(name, score)
  File "C:\Users\licong\Desktop\server\server\code\DAO\rankDAO.py", line 33, in SubmitRecord
    if score > result[i][2]:
IndexError: tuple index out of range
---------extra---------
recvfail2
[2018-12-12 19:19:11] ---------TraceErr---------
Traceback (most recent call last):
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 36, in run
    self.Recv(sData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 54, in Recv
    self.OnCommand(dPackData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 104, in OnCommand
    commandctrl.OnCommand(self, dData)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\__init__.py", line 15, in OnCommand
    oManager.OnCommand(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\mutexlock\__init__.py", line 18, in ___AutoLock
    ret = func(*args, **kwargs)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\manager.py", line 53, in OnCommand
    oFunc(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 117, in OnSubmit
    pubglobalmanager.CallManagerFunc("demo", "Submit", oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\pubglobalmanager.py", line 30, in CallManagerFunc
    return oFunc(*args)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 94, in Submit
    print("name = "+name+" score = "+score)
TypeError: cannot concatenate 'str' and 'int' objects
---------extra---------
recvfail2
[2018-12-12 19:24:44] ---------TraceErr---------
Traceback (most recent call last):
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 36, in run
    self.Recv(sData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 54, in Recv
    self.OnCommand(dPackData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 104, in OnCommand
    commandctrl.OnCommand(self, dData)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\__init__.py", line 15, in OnCommand
    oManager.OnCommand(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\mutexlock\__init__.py", line 18, in ___AutoLock
    ret = func(*args, **kwargs)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\manager.py", line 53, in OnCommand
    oFunc(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 119, in OnSubmit
    pubglobalmanager.CallManagerFunc("demo", "Submit", oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\pubglobalmanager.py", line 30, in CallManagerFunc
    return oFunc(*args)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 96, in Submit
    print("name = "+name+" score = "+score)
TypeError: cannot concatenate 'str' and 'int' objects
---------extra---------
recvfail2
[2018-12-12 19:25:21] ---------TraceErr---------
Traceback (most recent call last):
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 36, in run
    self.Recv(sData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 54, in Recv
    self.OnCommand(dPackData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 104, in OnCommand
    commandctrl.OnCommand(self, dData)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\__init__.py", line 15, in OnCommand
    oManager.OnCommand(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\mutexlock\__init__.py", line 18, in ___AutoLock
    ret = func(*args, **kwargs)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\manager.py", line 53, in OnCommand
    oFunc(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 119, in OnSubmit
    pubglobalmanager.CallManagerFunc("demo", "Submit", oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\pubglobalmanager.py", line 30, in CallManagerFunc
    return oFunc(*args)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 96, in Submit
    print("name = "+name+" score = "+score)
TypeError: cannot concatenate 'str' and 'int' objects
---------extra---------
recvfail2
[2018-12-12 19:27:00] ---------TraceErr---------
Traceback (most recent call last):
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 36, in run
    self.Recv(sData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 54, in Recv
    self.OnCommand(dPackData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 104, in OnCommand
    commandctrl.OnCommand(self, dData)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\__init__.py", line 15, in OnCommand
    oManager.OnCommand(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\mutexlock\__init__.py", line 18, in ___AutoLock
    ret = func(*args, **kwargs)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\manager.py", line 53, in OnCommand
    oFunc(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 119, in OnSubmit
    pubglobalmanager.CallManagerFunc("demo", "Submit", oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\pubglobalmanager.py", line 30, in CallManagerFunc
    return oFunc(*args)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 98, in Submit
    rank.SubmitRecord(name, score)
  File "C:\Users\licong\Desktop\server\server\code\DAO\rankDAO.py", line 33, in SubmitRecord
    if score > result[i][2]:
IndexError: tuple index out of range
---------extra---------
recvfail2
[2018-12-12 19:30:01] ---------TraceErr---------
Traceback (most recent call last):
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 36, in run
    self.Recv(sData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 54, in Recv
    self.OnCommand(dPackData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 104, in OnCommand
    commandctrl.OnCommand(self, dData)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\__init__.py", line 15, in OnCommand
    oManager.OnCommand(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\mutexlock\__init__.py", line 18, in ___AutoLock
    ret = func(*args, **kwargs)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\manager.py", line 53, in OnCommand
    oFunc(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 119, in OnSubmit
    pubglobalmanager.CallManagerFunc("demo", "Submit", oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\pubglobalmanager.py", line 30, in CallManagerFunc
    return oFunc(*args)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 98, in Submit
    rank.SubmitRecord(name, score)
  File "C:\Users\licong\Desktop\server\server\code\DAO\rankDAO.py", line 34, in SubmitRecord
    if score > result[i][2]:
IndexError: tuple index out of range
---------extra---------
recvfail2
[2018-12-12 19:31:53] ---------TraceErr---------
Traceback (most recent call last):
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 36, in run
    self.Recv(sData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 54, in Recv
    self.OnCommand(dPackData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 104, in OnCommand
    commandctrl.OnCommand(self, dData)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\__init__.py", line 15, in OnCommand
    oManager.OnCommand(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\mutexlock\__init__.py", line 18, in ___AutoLock
    ret = func(*args, **kwargs)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\manager.py", line 53, in OnCommand
    oFunc(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 119, in OnSubmit
    pubglobalmanager.CallManagerFunc("demo", "Submit", oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\pubglobalmanager.py", line 30, in CallManagerFunc
    return oFunc(*args)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 98, in Submit
    rank.SubmitRecord(name, score)
  File "C:\Users\licong\Desktop\server\server\code\DAO\rankDAO.py", line 34, in SubmitRecord
    if score > result[i][2] or not result[i][2]:
IndexError: tuple index out of range
---------extra---------
recvfail2
[2018-12-12 19:33:04] ---------TraceErr---------
Traceback (most recent call last):
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 36, in run
    self.Recv(sData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 54, in Recv
    self.OnCommand(dPackData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 104, in OnCommand
    commandctrl.OnCommand(self, dData)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\__init__.py", line 15, in OnCommand
    oManager.OnCommand(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\mutexlock\__init__.py", line 18, in ___AutoLock
    ret = func(*args, **kwargs)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\manager.py", line 53, in OnCommand
    oFunc(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 119, in OnSubmit
    pubglobalmanager.CallManagerFunc("demo", "Submit", oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\pubglobalmanager.py", line 30, in CallManagerFunc
    return oFunc(*args)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 98, in Submit
    rank.SubmitRecord(name, score)
  File "C:\Users\licong\Desktop\server\server\code\DAO\rankDAO.py", line 35, in SubmitRecord
    print result[i][2]
IndexError: tuple index out of range
---------extra---------
recvfail2
[2018-12-12 19:34:18] ---------TraceErr---------
Traceback (most recent call last):
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 36, in run
    self.Recv(sData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 54, in Recv
    self.OnCommand(dPackData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 104, in OnCommand
    commandctrl.OnCommand(self, dData)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\__init__.py", line 15, in OnCommand
    oManager.OnCommand(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\mutexlock\__init__.py", line 18, in ___AutoLock
    ret = func(*args, **kwargs)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\manager.py", line 53, in OnCommand
    oFunc(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 119, in OnSubmit
    pubglobalmanager.CallManagerFunc("demo", "Submit", oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\pubglobalmanager.py", line 30, in CallManagerFunc
    return oFunc(*args)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 98, in Submit
    rank.SubmitRecord(name, score)
  File "C:\Users\licong\Desktop\server\server\code\DAO\rankDAO.py", line 35, in SubmitRecord
    if score > result[i][2] or result[i][2] is None:
IndexError: tuple index out of range
---------extra---------
recvfail2
[2018-12-12 19:38:46] ---------TraceErr---------
Traceback (most recent call last):
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 36, in run
    self.Recv(sData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 54, in Recv
    self.OnCommand(dPackData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 104, in OnCommand
    commandctrl.OnCommand(self, dData)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\__init__.py", line 15, in OnCommand
    oManager.OnCommand(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\mutexlock\__init__.py", line 18, in ___AutoLock
    ret = func(*args, **kwargs)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\manager.py", line 53, in OnCommand
    oFunc(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 119, in OnSubmit
    pubglobalmanager.CallManagerFunc("demo", "Submit", oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\pubglobalmanager.py", line 30, in CallManagerFunc
    return oFunc(*args)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 98, in Submit
    rank.SubmitRecord(name, score)
  File "C:\Users\licong\Desktop\server\server\code\DAO\rankDAO.py", line 39, in SubmitRecord
    if score > result[i][2] or result[i][2] is None:
IndexError: tuple index out of range
---------extra---------
recvfail2
[2018-12-12 19:40:00] ---------TraceErr---------
Traceback (most recent call last):
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 36, in run
    self.Recv(sData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 54, in Recv
    self.OnCommand(dPackData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 104, in OnCommand
    commandctrl.OnCommand(self, dData)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\__init__.py", line 15, in OnCommand
    oManager.OnCommand(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\mutexlock\__init__.py", line 18, in ___AutoLock
    ret = func(*args, **kwargs)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\manager.py", line 53, in OnCommand
    oFunc(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 119, in OnSubmit
    pubglobalmanager.CallManagerFunc("demo", "Submit", oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\pubglobalmanager.py", line 30, in CallManagerFunc
    return oFunc(*args)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 98, in Submit
    rank.SubmitRecord(name, score)
  File "C:\Users\licong\Desktop\server\server\code\DAO\rankDAO.py", line 31, in SubmitRecord
    if result[0]:
IndexError: tuple index out of range
---------extra---------
recvfail2
